services:
  flagbin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "52420:52420"

    read_only: true
    tmpfs:
      - /tmp:size=300M,noexec

    pids_limit: 1024
    mem_limit: 400M
    cpus: 0.5

    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"

    restart: unless-stopped
