services:
  nev-php:
    restart: unless-stopped
    build: .
    pids_limit: 256
    mem_limit: 64M
    cpus: 0.5
    volumes:
      - ./src:/var/www/html/
      - ./receipts:/var/www/html/receipts
    ports:
      - 7000:80

  db:
    image: mariadb:10.6-jammy
    restart: always
    volumes:
      - "./db_data:/var/lib/mysql"
      - "./dbtables.sql:/docker-entrypoint-initdb.d/dbtables.sql"
    environment:
      MARIADB_ROOT_PASSWORD: ae0r87gh8a7werfh078hawefg
      MARIADB_DATABASE: nevalashka
      MARIADB_USER: nevalashka
      MARIADB_PASSWORD: 8aghsdf890ahfw98h2w3
