services:
  battlebots:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "55555:55555"

    read_only: true
    tmpfs:
      - /tmp:size=300M,noexec

    pids_limit: 1024
    mem_limit: 512M
    cpus: 1

    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"

    restart: unless-stopped
