WEAPONS = [ {"name": "Wooden sword", "attack_amount": 20, "description": "just a wooden sword", "lvl_req": 0},
            {"name": "Astral Wand", "attack_amount": 45, "description": "Channels cosmic energy to strike enemies from afar.", "lvl_req": 1},
            {"name": "Dragonheart Blade", "attack_amount": 60, "description": "Forged with dragonfire, this sword radiates raw power.", "lvl_req": 5},
            {"name": "Solar Boomerang", "attack_amount": 50, "description": "Returns after being thrown, burning enemies on its way back.", "lvl_req": 3},
            {"name": "Phantoblade", "attack_amount": 70, "description": "Can cut through any material and deflect magical attacks.", "lvl_req": 10},
            {"name": "Rose Thorn Whip", "attack_amount": 35, "description": "A flexible weapon made of enchanted thorns that sting like fire.", "lvl_req": 2},
            {"name": "Moon Khukuri", "attack_amount": 40, "description": "A curved blade infused with lunar magic for silent strikes.", "lvl_req": 4},
            {"name": "Earthquake Hammer", "attack_amount": 80, "description": "Crushes enemies and shakes the ground beneath them.", "lvl_req": 8},
            {"name": "Celestial Bow", "attack_amount": 55, "description": "Shoots arrows made of starlight that pierce through darkness.", "lvl_req": 6},
            {"name": "Aquamarine Trident", "attack_amount": 65, "description": "Harnesses the power of the ocean’s depths.", "lvl_req": 7},
            {"name": "Storm Scepter", "attack_amount": 60, "description": "Commands lightning and wind to strike down foes.", "lvl_req": 5},
            {"name": "Flameheart Dagger", "attack_amount": 30, "description": "A small but deadly blade that ignites upon drawing blood.", "lvl_req": 1},
            {"name": "Frost Crystal Staff", "attack_amount": 45, "description": "Freezes enemies on contact and slows their movement.", "lvl_req": 3},
            {"name": "Shadow Veil Scythe", "attack_amount": 75, "description": "Draws power from darkness to reap souls.", "lvl_req": 9},
            {"name": "Pixie Dust Mace", "attack_amount": 40, "description": "Releases bursts of glittering dust that confuse and damage.", "lvl_req": 2},
            {"name": "Starlight Rapier", "attack_amount": 50, "description": "A fast and elegant blade that blinds enemies with light.", "lvl_req": 4},
            {"name": "Twin Serpent Daggers", "attack_amount": 35, "description": "Two blades that move like snakes, striking from unexpected angles.", "lvl_req": 3},
            {"name": "Phoenix Feather Fan", "attack_amount": 45, "description": "Summons fiery winds that burn everything in their path.", "lvl_req": 5},
            {"name": "Thunderbolt Axe", "attack_amount": 70, "description": "Strikes with the force of a falling meteor.", "lvl_req": 7},
            {"name": "Crystal Bloom Cudgel", "attack_amount": 30, "description": "Grows sharper and stronger when used near flowers.", "lvl_req": 2},
            {"name": "Mirror of Illusion", "attack_amount": 20, "description": "Reflects enemy attacks and confuses their senses.", "lvl_req": 1},
            {"name": "Golden Lasso", "attack_amount": 25, "description": "Pulls enemies toward you or traps them in place.", "lvl_req": 1},
            {"name": "Wind Spirit Flute", "attack_amount": 35, "description": "Creates invisible gusts that slice through armor.", "lvl_req": 3},
            {"name": "Eclipse Blade", "attack_amount": 85, "description": "Only usable during eclipses; drains life from enemies.", "lvl_req": 10},
            {"name": "Dragon Claw Gauntlet", "attack_amount": 60, "description": "Enhances hand-to-hand combat with razor-sharp claws.", "lvl_req": 6},
            {"name": "Enchanted Lute", "attack_amount": 30, "description": "Stuns enemies with magical melodies before attacking.", "lvl_req": 2},
            {"name": "Obsidian Warhammer", "attack_amount": 90, "description": "A heavy weapon that shatters bones and shields alike.", "lvl_req": 9},
            {"name": "Whispering Cloak", "attack_amount": 15, "description": "Not a weapon per se, but allows stealthy attacks with bonus damage.", "lvl_req": 4},
            {"name": "Sun Crystal Pike", "attack_amount": 55, "description": "A long polearm that channels solar energy into piercing thrusts.", "lvl_req": 5},
            {"name": "Siren's Song Harp", "attack_amount": 40, "description": "Lulls enemies into a trance before striking.", "lvl_req": 3},
            {"name": "Blazing Meteor Hammer", "attack_amount": 85, "description": "Heats up and crashes down like a falling star.", "lvl_req": 8},
            {"name": "Crimson Lotus Blade", "attack_amount": 50, "description": "A flower-shaped sword that blooms mid-strike.", "lvl_req": 4},
            {"name": "Nightshade Throwing Stars", "attack_amount": 30, "description": "Tiny stars coated in poison that sap enemy strength.", "lvl_req": 2},
            {"name": "Lightning Ring", "attack_amount": 60, "description": "Generates arcs of electricity that jump between enemies.", "lvl_req": 6},
            {"name": "Frozen Rose Mace", "attack_amount": 45, "description": "Freezes enemies on impact and leaves frost trails.", "lvl_req": 5},
            {"name": "Silver Griffin Spear", "attack_amount": 65, "description": "Soars forward like a bird of prey, striking from above.", "lvl_req": 7},
            {"name": "Twilight Mirror Shield", "attack_amount": 20, "description": "Reflects half the damage taken back to the attacker.", "lvl_req": 3},
            {"name": "Dancing Butterflies Fan", "attack_amount": 35, "description": "Unleashes a flurry of magical butterfly strikes.", "lvl_req": 2},
            {"name": "Howling Wolf Claws", "attack_amount": 55, "description": "Grants enhanced speed and tearing power.", "lvl_req": 5},
            {"name": "Rainbow Prism Dagger", "attack_amount": 40, "description": "Shines brightly and deals random elemental damage.", "lvl_req": 4},
            {"name": "Mythic Phoenix Bow", "attack_amount": 70, "description": "Shoots flaming arrows that explode on impact.", "lvl_req": 7},
            {"name": "Emerald Vine Whip", "attack_amount": 30, "description": "Grows longer and stronger with each hit.", "lvl_req": 2},
            {"name": "Mystic Owl Staff", "attack_amount": 45, "description": "Increases wisdom and accuracy in battle.", "lvl_req": 3},
            {"name": "Inferno Scimitar", "attack_amount": 75, "description": "Blazing hot, it scorches everything it touches.", "lvl_req": 8},
            {"name": "Dreamcatcher Net", "attack_amount": 25, "description": "Traps enemies in illusions before striking.", "lvl_req": 2},
            {"name": "Storm Eagle Talons", "attack_amount": 60, "description": "Allows aerial attacks and dives with precision.", "lvl_req": 6},
            {"name": "Sapphire Frost Blade", "attack_amount": 50, "description": "Chills enemies and reduces their resistance to cold.", "lvl_req": 5},
            {"name": "Thunderbird Mace", "attack_amount": 70, "description": "Crackles with electricity and stuns on impact.", "lvl_req": 7},
            {"name": "Dragonfly Dart Launcher", "attack_amount": 40, "description": "Shoots tiny darts that swarm like insects.", "lvl_req": 3},
            {"name": "Celestial Moonstone Sword", "attack_amount": 80, "description": "Glowing with moonlight, it heals the user slightly on hit.", "lvl_req": 9},
            {"name": "Winx Heart Choker", "attack_amount": 10, "description": "A symbol of friendship and courage; boosts allies’ morale.", "lvl_req": 1}
]

SPELLS = [
     {"name": "Blast Ball", "description": "A small but powerful fireball that explodes on impact.", "lvl_req": 1, "attack_amount": 50},
     {"name": "Flame Shield", "description": "Creates a protective barrier of fire around the caster.", "lvl_req": 2, "attack_amount": 30},
     {"name": "Incandescent Sphere", "description": "A glowing orb of light energy that burns enemies over time.", "lvl_req": 4, "attack_amount": 60},
     {"name": "Sphere of Fire", "description": "Encases the enemy in a swirling ball of flames.", "lvl_req": 5, "attack_amount": 70},
     {"name": "Flame of Life", "description": "Restores health while igniting nearby enemies.", "lvl_req": 3, "attack_amount": 40},
     {"name": "Full Power Fire", "description": "Unleashes the caster’s full magical power in a fiery blast.", "lvl_req": 8, "attack_amount": 80},
     {"name": "Heat Wave", "description": "Emits a wave of intense heat that weakens enemies.", "lvl_req": 4, "attack_amount": 55},
     {"name": "Triple Blast", "description": "Releases three consecutive magical blasts in quick succession.", "lvl_req": 6, "attack_amount": 65},
     {"name": "Fire Wall", "description": "Summons a wall of fire that blocks attacks and damages enemies.", "lvl_req": 7, "attack_amount": 75},
     {"name": "Wave Shield", "description": "Generates a shimmering shield that absorbs part of incoming damage.", "lvl_req": 2, "attack_amount": 35},
     {"name": "Sonic Shake", "description": "Causes vibrations that disorient and confuse enemies.", "lvl_req": 3, "attack_amount": 45},
     {"name": "Sonic Blast", "description": "Releases a shockwave of sound that knocks enemies back.", "lvl_req": 5, "attack_amount": 60},
     {"name": "Virtual Protection", "description": "Creates an illusionary copy of the caster to distract enemies.", "lvl_req": 2, "attack_amount": 25},
     {"name": "Dragon Fire", "description": "Mimics the breath of a dragon, unleashing a devastating stream of flame.", "lvl_req": 10, "attack_amount": 90},
     {"name": "Inspirations and References", "description": "Boosts allies’ focus and accuracy during battle.", "lvl_req": 3, "attack_amount": 40},
     {"name": "Autumn's Wind", "description": "Calls forth gusts of wind that carry falling leaves to confuse enemies.", "lvl_req": 4, "attack_amount": 50},
     {"name": "Bloom", "description": "Causes magical flowers to grow rapidly, entangling enemies.", "lvl_req": 2, "attack_amount": 35},
     {"name": "Breath of Nature", "description": "Channels natural energy to heal allies and harm enemies.", "lvl_req": 6, "attack_amount": 60},
     {"name": "Bright Heart", "description": "Strengthens morale and temporarily boosts magic power.", "lvl_req": 1, "attack_amount": 20},
     {"name": "Convergence", "description": "Combines multiple magical energies into one concentrated beam.", "lvl_req": 8, "attack_amount": 70},
     {"name": "Dawn of Light", "description": "Summons a burst of radiant light that blinds and burns foes.", "lvl_req": 9, "attack_amount": 85},
     {"name": "Defender Plate", "description": "Hardens the caster’s skin like armor, reducing physical damage.", "lvl_req": 2, "attack_amount": 30},
     {"name": "Army of Darkness", "description": "Summons shadow creatures to fight alongside the caster.", "lvl_req": 10, "attack_amount": 100},
     {"name": "Moonbeam Strike", "description": "Channels moonlight into a piercing ray of light.", "lvl_req": 5, "attack_amount": 55},
     {"name": "Frostbite", "description": "Freezes the enemy in place and deals cold damage over time.", "lvl_req": 4, "attack_amount": 45},
     {"name": "Thundercall", "description": "Summons a lightning bolt from the sky to strike a target.", "lvl_req": 6, "attack_amount": 65},
     {"name": "Tidal Surge", "description": "Rides a wave of water to knock enemies off balance.", "lvl_req": 5, "attack_amount": 60},
     {"name": "Whirlwind Spiral", "description": "Generates a vortex of wind that pulls enemies toward the center.", "lvl_req": 4, "attack_amount": 50},
     {"name": "Crystal Spike", "description": "Forms sharp crystal shards that impale enemies.", "lvl_req": 3, "attack_amount": 40},
     {"name": "Sunburst", "description": "Releases a massive explosion of sunlight energy.", "lvl_req": 9, "attack_amount": 90},
     {"name": "Healing Bloom", "description": "Restores hp with the power of enchanted flowers.", "lvl_req": 1, "attack_amount": 10},
     {"name": "Pixie Dust Cloud", "description": "Covers the area in sparkling dust that confuses enemies.", "lvl_req": 2, "attack_amount": 30},
     {"name": "Stellar Flash", "description": "Blinds enemies with a flash of starlight before attacking.", "lvl_req": 6, "attack_amount": 70},
     {"name": "Eclipse Pulse", "description": "Drains energy from enemies under the shadow of an eclipse.", "lvl_req": 8, "attack_amount": 80},
     {"name": "Mirror Reflect", "description": "Reflects half of the damage taken back to the attacker.", "lvl_req": 3, "attack_amount": 25},
     {"name": "Storm Chain", "description": "Sends arcs of lightning between multiple enemies.", "lvl_req": 7, "attack_amount": 75},
     {"name": "Shadow Step", "description": "Teleports short distances, leaving behind a cloud of darkness.", "lvl_req": 4, "attack_amount": 35},
     {"name": "Golden Feather Flight", "description": "Allows brief flight and dodging attacks mid-air.", "lvl_req": 2, "attack_amount": 20},
     {"name": "Dragon Roar", "description": "Emits a sonic roar that stuns enemies momentarily.", "lvl_req": 5, "attack_amount": 60},
     {"name": "Celestial Spark", "description": "Generates bursts of cosmic energy that hit multiple targets.", "lvl_req": 4, "attack_amount": 45},
     {"name": "Ice Mirror", "description": "Reflects enemy projectiles back at them using an ice surface.", "lvl_req": 3, "attack_amount": 30},
     {"name": "Phoenix Rebirth", "description": "Revives the caster once after being defeated.", "lvl_req": 7, "attack_amount": 15},
     {"name": "Aurora Beam", "description": "Shoots a colorful beam of northern lights energy.", "lvl_req": 5, "attack_amount": 55},
     {"name": "Witch’s Circle", "description": "Creates a protective circle that absorbs minor spells.", "lvl_req": 2, "attack_amount": 20},
     {"name": "Meteor Swarm", "description": "Calls down multiple meteors to crash into the battlefield.", "lvl_req": 10, "attack_amount": 95},
     {"name": "Starfall Barrage", "description": "Summons a rain of shooting stars across the field.", "lvl_req": 9, "attack_amount": 85},
     {"name": "Glimmer Veil", "description": "Cloaks the caster in shimmering light, reducing visibility.", "lvl_req": 3, "attack_amount": 25},
     {"name": "Heartfire", "description": "Empowers allies with warmth and courage, increasing their strength.", "lvl_req": 4, "attack_amount": 50},
     {"name": "Dreamweaver", "description": "Puts enemies into a trance-like state, slowing their actions.", "lvl_req": 4, "attack_amount": 40},
     {"name": "Winx Magic Boost", "description": "Enhances all allies' magical abilities for a short time.", "lvl_req": 1, "attack_amount": 10}
]

from bisect import bisect_right
from random import random
from models.db import Character
get_level_from_xp = lambda  current_xp: bisect_right([0, 10, 56, 155, 320, 559, 881, 1296, 1810, 2430, 3162], current_xp) - 1


def character_strength(someone :Character):
     if someone.type == 'Melee':

          result = ((get_level_from_xp(someone.xp) * 10 + sum([WEAPONS[item]['attack_amount'] if get_level_from_xp(someone.xp) >= WEAPONS[item]['lvl_req'] else 0 for item in someone.inventory])) / 10)
     else:
          result = ((get_level_from_xp(someone.xp) * 10 + sum([SPELLS[item]['attack_amount'] if get_level_from_xp(someone.xp) >= SPELLS[item]['lvl_req'] - 1 else 0 for item in someone.spells])) / 10)
     return result

def character_result(someone :Character):
         return character_strength(someone) * random()

def model_to_dict(model):
    return {c.name: getattr(model, c.name) for c in model.__table__.columns}

MONSTERS = [
    {'name': "Glitter Gloom", 'difficulty': 1},
    {'name': "Pixie Shadow", 'difficulty': 2},
    {'name': "Candy Cursed Sprout", 'difficulty': 1},
    {'name': "Mystic Mothwing", 'difficulty': 3},
    {'name': "Whispering Thornvine", 'difficulty': 4},
    {'name': "Banshee Bloom", 'difficulty': 5},
    {'name': "Storm Petal", 'difficulty': 6},
    {'name': "Gloomspire Bat", 'difficulty': 2},
    {'name': "Feyfang Spider", 'difficulty': 3},
    {'name': "Crystalshade Serpent", 'difficulty': 7},
    {'name': "Moonlit Banshee", 'difficulty': 6},
    {'name': "Duskfeather Owlbeast", 'difficulty': 5},
    {'name': "Flamepetal Hydra", 'difficulty': 8},
    {'name': "Starlight Manticore", 'difficulty': 9},
    {'name': "Frostblossom Nymph", 'difficulty': 4},
    {'name': "Nightglow Pixie", 'difficulty': 3},
    {'name': "Thunderleaf Dryad", 'difficulty': 6},
    {'name': "Ebonroot Treant", 'difficulty': 7},
    {'name': "Siren Lily", 'difficulty': 5},
    {'name': "Shadowbloom Faerie", 'difficulty': 6},
    {'name': "Emberwing Fairy Drake", 'difficulty': 8},
    {'name': "Aurora Sprite", 'difficulty': 4},
    {'name': "Vortex Wraith", 'difficulty': 9},
    {'name': "Dreamweaver Imp", 'difficulty': 3},
    {'name': "Twilight Sylph", 'difficulty': 5},
    {'name': "Obsidian Nyx", 'difficulty': 7},
    {'name': "Zephyr Stalker", 'difficulty': 6},
    {'name': "Venomthorn Vine", 'difficulty': 7},
    {'name': "Lunar Howler", 'difficulty': 5},
    {'name': "Celestial Basilisk", 'difficulty': 9},
    {'name': "Sunbeam Ghoul", 'difficulty': 4},
    {'name': "Rainbow Shade", 'difficulty': 3},
    {'name': "Mirage Muse", 'difficulty': 6},
    {'name': "Ashen Harpy", 'difficulty': 7},
    {'name': "Tide Whisperer", 'difficulty': 5},
    {'name': "Chaos Nymph", 'difficulty': 8},
    {'name': "Witch Willow", 'difficulty': 4},
    {'name': "Dreadbloom Spirit", 'difficulty': 6},
    {'name': "Eclipse Demoness", 'difficulty': 9},
    {'name': "Crimson Fae", 'difficulty': 5},
    {'name': "Frozen Fury", 'difficulty': 7},
    {'name': "Blazewing Phoenixling", 'difficulty': 8},
    {'name': "Murkwater Merrow", 'difficulty': 6},
    {'name': "Illusionist Sprite", 'difficulty': 5},
    {'name': "Echo Wyrm", 'difficulty': 7},
    {'name': "Spectral Pixeling", 'difficulty': 4},
    {'name': "Toxic Tulip", 'difficulty': 3},
    {'name': "Voidbloom Witch", 'difficulty': 8},
    {'name': "Silverthorn Beast", 'difficulty': 6},
    {'name': "Inferno Sylph", 'difficulty': 9}
]